// Code generated by 'yaegi extract github.com/coredns/coredns/request'. DO NOT EDIT.

package corednsyaegi

import (
	"github.com/coredns/coredns/request"
	"reflect"
)

func init() {
	Symbols["github.com/coredns/coredns/request/request"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewScrubWriter": reflect.ValueOf(request.NewScrubWriter),

		// type definitions
		"Request":     reflect.ValueOf((*request.Request)(nil)),
		"ScrubWriter": reflect.ValueOf((*request.ScrubWriter)(nil)),
	}
}
