// Code generated by 'yaegi extract github.com/coredns/coredns/plugin/pkg/rcode'. DO NOT EDIT.

package custom

import (
	"github.com/coredns/coredns/plugin/pkg/rcode"
	"reflect"
)

func init() {
	Symbols["github.com/coredns/coredns/plugin/pkg/rcode/rcode"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ToString": reflect.ValueOf(rcode.ToString),
	}
}
