// Code generated by 'yaegi extract github.com/coredns/coredns/plugin/metrics'. DO NOT EDIT.

package custom

import (
	"github.com/coredns/coredns/plugin/metrics"
	"reflect"
)

func init() {
	Symbols["github.com/coredns/coredns/plugin/metrics/metrics"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ListenAddr":  reflect.ValueOf(&metrics.ListenAddr).Elem(),
		"New":         reflect.ValueOf(metrics.New),
		"NewRecorder": reflect.ValueOf(metrics.NewRecorder),
		"WithServer":  reflect.ValueOf(metrics.WithServer),
		"WithView":    reflect.ValueOf(metrics.WithView),

		// type definitions
		"Metrics":  reflect.ValueOf((*metrics.Metrics)(nil)),
		"Recorder": reflect.ValueOf((*metrics.Recorder)(nil)),
	}
}
